#!/bin/sh

echo Pulling CT.
git pull

echo Fetching upstream Frogatto and checking out.
git fetch upstream

git checkout upstream/master FreeMono.ttf
git checkout upstream/master .gitignore
git checkout upstream/master ct

git checkout upstream/master data/achievements.cfg        
git checkout upstream/master data/leaderboards.cfg
git checkout upstream/master data/control_schemes.cfg     
git checkout upstream/master data/dialog_font.cfg         
git checkout upstream/master data/level-template.cfg
git checkout upstream/master data/dialog_font.ja.cfg      
git checkout upstream/master data/list-functions.cfg
git checkout upstream/master data/dialog_font.zh_CN.cfg   
git checkout upstream/master data/number_font.cfg               
git checkout upstream/master data/number_font_large.cfg
git checkout upstream/master data/editor.cfg            
git checkout upstream/master data/fonts.cfg        
git checkout upstream/master data/fonts.ja.cfg            
git checkout upstream/master data/outline_font.cfg
git checkout upstream/master data/fonts.zh_CN.cfg         
git checkout upstream/master data/outline_font.ja.cfg
git checkout upstream/master data/functions.cfg           
git checkout upstream/master data/outline_font.zh_CN.cfg
git checkout upstream/master data/geometry-functions.cfg  
git checkout upstream/master data/powerups.cfg   
git checkout upstream/master data/gui.cfg                 
git checkout upstream/master data/schema.cfg
git checkout upstream/master data/label_font.cfg     
git checkout upstream/master data/label_font.ja.cfg  
git checkout upstream/master data/label_font.zh_CN.cfg    
git checkout upstream/master data/time-functions.cfg

git checkout upstream/master data/editor

git checkout upstream/master data/gui

git checkout upstream/master data/level/cube-trains

git checkout upstream/master data/object_prototypes

git checkout upstream/master data/objects/effects

git checkout upstream/master data/objects/experimental

git checkout upstream/master data/objects/hud-elements

git checkout upstream/master data/shaders

git checkout upstream/master images/window-icon.png

git checkout upstream/master images/backgrounds/loading_screen.png

git checkout upstream/master images/effects/particles.png

git checkout upstream/master images/experimental/cube\ trains  
git checkout upstream/master images/experimental/spiderbot.png

git checkout upstream/master images/gui

git checkout upstream/master locale
	
git checkout upstream/master MacOS
	
git checkout upstream/master po

git checkout upstream/master .tx

echo Done.